#!/bin/bash

echo "[INFO]: 'git add .'"
git add . 1>/dev/null

echo "[INFO]: 'git commit -m \"TEST\"'"
git commit -m "TEST" 1>/dev/null

echo "[INFO]: 'git push'"
git push 1>/dev/null

echo "Complete!"
